version: '3'
services:
    api:
        container_name: thoughts_api
        image: node:12.18.4
        environment:
            - PGHOST=db
            - PGUSER=admin
            - PGDATABASE=dbdata
            - PGPASSWORD=scottdan
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./api
              target: /code
        working_dir: /code
        command: bash -c "npm install && npm run dev"
        depends_on:
            - db
    db:
        container_name: thoughts_db
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_DB=dbdata
            - POSTGRES_PASSWORD=scottdan
        volumes:
            - "dbdata:/var/lib/postgresql/data"
            - "./db:/docker-entrypoint-initdb.d/:ro"
        working_dir: /code
volumes:
    dbdata:
